### PR TITLE
feat(i18n): improvment on feedback, create custom css file

### PR DESCRIPTION
**Pull request by marianfoo**
improvment based on feedback in #7
index page is now the overview page
alternative dot notation in propertie files
first suggestion for custom css to display good/bad practice more visually
new "advanced features" page

### CODE REVIEW

**Review by vobu — COMMENTED** [review]
content-wise all fine, nice explanations!
let's align on the css/optics in the next status meeting of the working group
@marianfoo please demo your content in bespoken meeting

**Comment by vobu** [comment]
moved to `draft` mode until #15 content contributions are done

**Comment by vobu** [comment]
any chance we can get this in @Rob077 ?

**Review by areichPuC — APPROVED** [review]
everything fine.

**Pull request merged**
