### PR TITLE
Tooling

### LINKED ISSUE #84: New Topic Tooling

### PR DESCRIPTION
**Pull request by treee111**
- overview of Tooling
- page for Tooling incl. graphic

### CODE REVIEW

**Comment by marianfoo** [comment]
Hi @treee111 
what´s your current status here?

**Comment by treee111** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by treee111** [comment]
Hi @vobu,
is this file like that what we talked about together?
This is a draft, should be made nicer, but I want to get sure the direction is OK.
https://github.com/treee111/UI5-Best-Practice/blob/tooling/docs/tooling/img/tooling_overview.png

**Comment by marianfoo** [comment]
Hey @treee111 ,
what is the current status here?
Do you need support in any form?

**Comment by treee111** [comment]
Hi @marianfoo,
thanks for the reminder! I'm away for two weeks and try to do and push stuff here to look into together.
I have a bad feeling for not getting done anything here but the last months have been way to busy...

**Comment by marianfoo** [comment]
@treee111 no worries!
We have a contributor meeting on friday. I sent you a invite. You may have time for that.
If you need any other help, just tell me.

**Comment by marianfoo** [comment]
Hey @treee111 ,
no matter what your current state is, if already have additional content, just commit it here.
I would have possibly also a topic what I would like to contribute here.
But I don't want to mess up your structure.
Just commit when you have time.
Thanks!

**Comment by treee111** [comment]
Hi @marianfoo, commited the updated picture with the input from our discussion last year.
The next step is to check if Marmaid can run with this repo to do picture in a nicer way, only had a brief look onto.
Don't hesitate to change the structure! I think another point of view can help here!

**Pull request closed without merging**
