### PR TITLE
Change markdown procesor

### PR DESCRIPTION
**Pull request by marianfoo**
- change Markdown Processor to kramdown to use [IAL](https://kramdown.gettalong.org/syntax.html#block-ials)
- Fix Bad / Good Example Template
- Fix Captions of Images

### CODE REVIEW

**Comment by vobu** [comment]
you might want to separate the md proc change from actual content/formatting changes.
the md proc change we could just merge in on the fly while your content changes might take a while :)

**Comment by marianfoo** [comment]
> you might want to separate the md proc change from actual content/formatting changes.
> the md proc change we could just merge in on the fly while your content changes might take a while :)

All modifications are due to changes in the Markdown processor.
There are no changes to the content itself.
Doesn't it make sense then to put all this in a single pull request?

**Comment by vobu** [comment]
> > you might want to separate the md proc change from actual content/formatting changes.
> > the md proc change we could just merge in on the fly while your content changes might take a while :)
> 
> All modifications are due to changes in the Markdown processor.
> There are no changes to the content itself.
> Doesn't it make sense then to put all this in a single pull request?

ah, ok, i thought stuff like https://github.com/1DSAG/UI5-Best-Practice/pull/33/files#diff-46d26bd1e5675ebfdd198833d146d87a617b19efdb423bc97430e59425c2b8edL80 were also a formatting change. but when it's related to the md-proc change, i stand corrected. will merge now.

**Comment by marianfoo** [comment]
we can still discuss it tomorrow, but it´s ready to merge

**Review by vobu — APPROVED** [review]
as discussed in the meeting -> good to go

**Pull request merged**
