### PR TITLE
docs(i18n): add supportedLocale and fallbackLocale

### PR DESCRIPTION
**Pull request by marianfoo**
new section in i18n for supportedLocale and fallbackLocale since version 1.77

### CODE REVIEW

**Comment by marianfoo** [comment]
@dscbs reminder

**Comment by marianfoo** [comment]
@dscbs reminder

**Comment by marianfoo** [comment]
@dscbs reminder

**Review by dscbs — APPROVED** [review]
Looks good!

**Comment by marianfoo** [comment]
@dscbs 🎉👍

**Pull request merged**
